{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "92a5bf92",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "\n",
    "def run_simulation(ro, lambda_val, P0, map_ref, sigma,\n",
    "                   a1_ini, b1_ini, bm_ini, d_ini, m_ini,\n",
    "                   k_change, a1_new, b1_new, bm_new, d_new, m_new,\n",
    "                   N_MC=50):\n",
    "\n",
    "    N = 500\n",
    "    yref = P0 - map_ref\n",
    "\n",
    "    d_vetor = [2, 3, 4, 5]\n",
    "    m_vetor = [2, 3, 4, 5]\n",
    "\n",
    "    teta_real_ini = [a1_ini, b1_ini, bm_ini]\n",
    "\n",
    "    cfg = [\n",
    "        ('GPC Fixo', lambda: Controlador_GPC_Fixo([a1_ini, b1_ini, bm_ini], d_ini, m_ini, ro)),\n",
    "        ('GPC Adaptativo', lambda: Controlador_GPC_Adaptativo(ro)),\n",
    "        ('3.2 Perturbação', lambda: Controlador_32_Perturbacao()),\n",
    "        ('3.3 Restrições', lambda: Controlador_33_Restricoes()),\n",
    "        ('3.5 IDC', lambda: Controlador_35_Inovacoes(lambda_idc=0.5)),\n",
    "    ]\n",
    "\n",
    "    res = {}\n",
    "\n",
    "    for nome, make_ctrl in cfg:\n",
    "        res[nome] = {\n",
    "            'all_map': np.zeros((N_MC, N)),\n",
    "            'all_i': np.zeros((N_MC, N)),\n",
    "            'incerteza': np.zeros((N, 4))\n",
    "        }\n",
    "\n",
    "        for mc in range(N_MC):\n",
    "\n",
    "            paciente = Paciente(teta_real_ini, d_ini, m_ini, P0, sigma)\n",
    "            identificador = Identificador(lambda_val, d_vetor, m_vetor, N)\n",
    "            ctrl = make_ctrl()\n",
    "\n",
    "            I_pac = 0.0\n",
    "\n",
    "            for k in range(N):\n",
    "\n",
    "                if k == k_change:\n",
    "                    paciente.teta_real = [a1_new, b1_new, bm_new]\n",
    "\n",
    "                MAP, P_med, _ = paciente.step(I_pac)\n",
    "\n",
    "                teta_est, d_est, m_est, vetor_inc, _, P_melhor = identificador.RLS(P_med, I_pac)\n",
    "\n",
    "                var_b1 = vetor_inc[identificador.ind_melhor]\n",
    "\n",
    "                I_pac = ctrl.calcular_controle(yref, P_med, teta_est, d_est, m_est, var_b1, P_melhor)\n",
    "\n",
    "                res[nome]['all_map'][mc, k] = MAP\n",
    "                res[nome]['all_i'][mc, k] = I_pac\n",
    "                res[nome]['incerteza'][k] = vetor_inc\n",
    "\n",
    "    return res"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
