{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bb10f790",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "\n",
    "class Controlador_35_Inovacoes:\n",
    "    \"\"\"\n",
    "    Seção 3.5 de Jamier — IDC (Milito e Cadorin, 1982): Eq. 3.13.\n",
    "    Compromisso entre controlador cauteloso (λ=1) e equivalente à certeza (λ=0).\n",
    "    Usa P_cov diretamente — sem suavização, sem energia intermediária.\n",
    "    \"\"\"\n",
    "    def __init__(self, lambda_idc=0.5):\n",
    "        self.lambda_idc = lambda_idc\n",
    "        self.k          = 0\n",
    "        self.I_ante_1   = 0.0\n",
    "        self.I_histo    = np.zeros(100)\n",
    "\n",
    "    def calcular_controle(self, P_ref, P_k_medido, teta_est, d_est, m_est, inovacao_k, P_cov):\n",
    "        self.k += 1\n",
    "        a1_est, b1_est, bm_est = teta_est\n",
    "        b1_ctrl = max(b1_est, 0.01)\n",
    "\n",
    "        if self.k <= 10:\n",
    "            PRBS = 10.0\n",
    "            if self.k > 5:\n",
    "                PRBS = 60 - (60 / 3.8) * abs(b1_est)\n",
    "            I_calculado = PRBS if random.random() > 0.5 else 0.0\n",
    "            I_calculado = np.clip(I_calculado, 0, 180)\n",
    "            self.I_histo = np.roll(self.I_histo, 1);  self.I_histo[0] = I_calculado\n",
    "            self.I_ante_1 = I_calculado\n",
    "            return I_calculado\n",
    "\n",
    "        k0 = (-a1_est) ** d_est * P_k_medido\n",
    "        for i in range(1, d_est):\n",
    "            t1 = b1_ctrl * self.I_histo[i]         if i         < len(self.I_histo) else 0.0\n",
    "            t2 = bm_est  * self.I_histo[m_est + i] if m_est + i < len(self.I_histo) else 0.0\n",
    "            k0 += (-a1_est) ** i * (t1 + t2)\n",
    "        if m_est < len(self.I_histo):\n",
    "            k0 += bm_est * self.I_histo[m_est]\n",
    "\n",
    "        # Eq. 3.13 de Jamier — IDC\n",
    "        lam     = self.lambda_idc\n",
    "        p_b1 = P_cov[1, 1]  # limita para não zerar o controle no início\n",
    "        IP_teta = P_cov[1, :] @ teta_est\n",
    "\n",
    "        num = b1_ctrl * (P_ref - k0) + (1 - lam) * IP_teta + (1 - lam) * p_b1 * self.I_ante_1\n",
    "        den = b1_ctrl ** 2 + (1 - lam) * p_b1\n",
    "\n",
    "        I_calculado = np.clip(num / max(den, 1e-6), 0, 180)\n",
    "\n",
    "        self.I_histo = np.roll(self.I_histo, 1);  self.I_histo[0] = I_calculado\n",
    "        self.I_ante_1 = I_calculado\n",
    "        return I_calculado\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
