{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8b468b12",
   "metadata": {},
   "outputs": [],
   "source": [
    "class Controlador_32_Perturbacao:\n",
    "    \"\"\"\n",
    "    Seção 3.2 de Jamier: u_perturb(t) = u_ca(t) + u_p(t)\n",
    "    A base é o controlador CAUTELOSO (Eq. 2.23), não o GPC sem ro.\n",
    "    O sinal de perturbação u_p é somado para garantir excitação persistente.\n",
    "    \"\"\"\n",
    "    def __init__(self, amplitude=8.0, taxa_decaimento=0.997, seed=None):\n",
    "        self.k        = 0\n",
    "        self.I_ante_1 = 0.0\n",
    "        self.I_histo  = np.zeros(100)\n",
    "        self._amp     = amplitude\n",
    "        self._decay   = taxa_decaimento\n",
    "        self._rng     = np.random.default_rng(seed)\n",
    "\n",
    "    def calcular_controle(self, P_ref, P_k_medido, teta_est, d_est, m_est, inovacao_k, P_cov):\n",
    "        self.k += 1\n",
    "        a1_est, b1_est, bm_est = teta_est\n",
    "        b1_ctrl = max(b1_est, 0.01)\n",
    "\n",
    "        if self.k <= 10:\n",
    "            I_calculado = 30.0 if self._rng.integers(0, 2) == 1 else 0.0\n",
    "            I_calculado = np.clip(I_calculado, 0, 180)\n",
    "            self.I_histo = np.roll(self.I_histo, 1);  self.I_histo[0] = I_calculado\n",
    "            self.I_ante_1 = I_calculado\n",
    "            return I_calculado\n",
    "\n",
    "        # K0 padrão\n",
    "        k0 = (-a1_est) ** d_est * P_k_medido\n",
    "        for i in range(1, d_est):\n",
    "            t1 = b1_ctrl * self.I_histo[i]         if i         < len(self.I_histo) else 0.0\n",
    "            t2 = bm_est  * self.I_histo[m_est + i] if m_est + i < len(self.I_histo) else 0.0\n",
    "            k0 += (-a1_est) ** i * (t1 + t2)\n",
    "        if m_est < len(self.I_histo):\n",
    "            k0 += bm_est * self.I_histo[m_est]\n",
    "\n",
    "        # --- Controlador cauteloso (Eq. 2.23) como base ---\n",
    "        # p_b1: variância de b1 da matriz de covariância\n",
    "        # Cauteloso (Eq. 2.23) — base do 3.2\n",
    "        p_b1 = P_cov[1, 1]  # limita para não zerar o controle no início\n",
    "        IP_teta = P_cov[1, :] @ teta_est\n",
    "\n",
    "        num_ca = b1_ctrl * (P_ref - k0) + IP_teta + p_b1 * self.I_ante_1\n",
    "        den_ca = b1_ctrl ** 2 + p_b1\n",
    "        u_ca   = num_ca / max(den_ca, 1e-6)\n",
    "\n",
    "        # --- Perturbação PRBS — dualidade explícita (Seção 3.2) ---\n",
    "        u_p       = self._amp * (self._rng.integers(0, 2) * 2 - 1)\n",
    "        self._amp *= self._decay\n",
    "\n",
    "        I_calculado = np.clip(u_ca + u_p, 0, 180)\n",
    "        self.I_histo = np.roll(self.I_histo, 1);  self.I_histo[0] = I_calculado\n",
    "        self.I_ante_1 = I_calculado\n",
    "        return I_calculado"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
