{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a1af652d",
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "class Controlador_33_Restricoes:\n",
    "    \"\"\"\n",
    "    Seção 3.3 de Jamier — Jacobs e Hughes (1974): Eq. 3.2.\n",
    "    Base: controlador cauteloso (Eq. 2.23).\n",
    "    Restrição: impede que |u_ca| caia abaixo de u_lim,\n",
    "    evitando o fenômeno de turn-off.\n",
    "    \"\"\"\n",
    "    def __init__(self, u_lim=5.0):\n",
    "        self.u_lim    = u_lim   # limite mínimo de excitação\n",
    "        self.k        = 0\n",
    "        self.I_ante_1 = 0.0\n",
    "        self.I_histo  = np.zeros(100)\n",
    "\n",
    "    def calcular_controle(self, P_ref, P_k_medido, teta_est, d_est, m_est, inovacao_k, P_cov):\n",
    "        self.k += 1\n",
    "        a1_est, b1_est, bm_est = teta_est\n",
    "        b1_ctrl = max(b1_est, 0.01)\n",
    "\n",
    "        if self.k <= 10:\n",
    "            PRBS = 10.0\n",
    "            if self.k > 5:\n",
    "                PRBS = 60 - (60 / 3.8) * abs(b1_est)\n",
    "            I_calculado = PRBS if random.random() > 0.5 else 0.0\n",
    "            I_calculado = np.clip(I_calculado, 0, 180)\n",
    "            self.I_histo = np.roll(self.I_histo, 1);  self.I_histo[0] = I_calculado\n",
    "            self.I_ante_1 = I_calculado\n",
    "            return I_calculado\n",
    "\n",
    "        k0 = (-a1_est) ** d_est * P_k_medido\n",
    "        for i in range(1, d_est):\n",
    "            t1 = b1_ctrl * self.I_histo[i]         if i         < len(self.I_histo) else 0.0\n",
    "            t2 = bm_est  * self.I_histo[m_est + i] if m_est + i < len(self.I_histo) else 0.0\n",
    "            k0 += (-a1_est) ** i * (t1 + t2)\n",
    "        if m_est < len(self.I_histo):\n",
    "            k0 += bm_est * self.I_histo[m_est]\n",
    "\n",
    "        # Base: cauteloso real (Eq. 2.23)\n",
    "        p_b1    = P_cov[1, 1]\n",
    "        IP_teta = P_cov[1, :] @ teta_est\n",
    "\n",
    "        num_ca = b1_ctrl * (P_ref - k0) + IP_teta + p_b1 * self.I_ante_1\n",
    "        den_ca = b1_ctrl ** 2 + p_b1\n",
    "        u_ca   = num_ca / max(den_ca, 1e-6)\n",
    "\n",
    "        # Restrição de Jacobs e Hughes (Eq. 3.2):\n",
    "        # se o cauteloso for fraco demais, força u_lim para manter excitação\n",
    "        if abs(u_ca) < self.u_lim:\n",
    "            I_calculado = self.u_lim * np.sign(u_ca) if u_ca != 0 else self.u_lim\n",
    "        else:\n",
    "            I_calculado = u_ca\n",
    "\n",
    "        I_calculado = np.clip(I_calculado, 0, 180)\n",
    "        self.I_histo = np.roll(self.I_histo, 1);  self.I_histo[0] = I_calculado\n",
    "        self.I_ante_1 = I_calculado\n",
    "        return I_calculado"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
