{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ee6f3844",
   "metadata": {},
   "outputs": [],
   "source": [
    "class Identificador:\n",
    "    def __init__(self, lambda_val, d_vetor, m_vetor, N_sim):\n",
    "        self.lambda_val  = lambda_val\n",
    "        self.d_vetor     = np.array(d_vetor)\n",
    "        self.m_vetor     = np.array(m_vetor)\n",
    "        self.k           = 0\n",
    "        self.teta_ea     = np.zeros(12)\n",
    "        self.Pant        = np.kron(np.eye(4), 10 * np.eye(3))\n",
    "        self.histo_erro  = np.zeros((N_sim, 4))\n",
    "        self.fator       = np.zeros(4)\n",
    "        self.P_histo     = np.zeros(100)\n",
    "        self.I_histo     = np.zeros(100)\n",
    "        self.ind_melhor  = 0\n",
    "        self.teta_melhor = np.zeros(3)\n",
    "\n",
    "    def RLS(self, P_k_medido, I_k_anterior):\n",
    "        self.k += 1\n",
    "        self.P_histo = np.roll(self.P_histo, 1);  self.P_histo[0] = P_k_medido\n",
    "        self.I_histo = np.roll(self.I_histo, 1);  self.I_histo[0] = I_k_anterior\n",
    "\n",
    "        fia = np.zeros(12)\n",
    "        for j in range(4):\n",
    "            ind  = 3 * j\n",
    "            d_j, m_j = self.d_vetor[j], self.m_vetor[j]\n",
    "            fia[ind] = -self.P_histo[1]\n",
    "            if d_j - 1       < len(self.I_histo): fia[ind + 1] = self.I_histo[d_j - 1]\n",
    "            if d_j + m_j - 1 < len(self.I_histo): fia[ind + 2] = self.I_histo[d_j + m_j - 1]\n",
    "\n",
    "        Soma_mi = 0\n",
    "        for j in range(4):\n",
    "            sl    = slice(3*j, 3*j+3)\n",
    "            fia_j = fia[sl];  Pant_j = self.Pant[sl, sl]\n",
    "            den   = self.lambda_val + fia_j @ Pant_j @ fia_j\n",
    "            if den == 0: den = 1e-9\n",
    "            kk_j  = (Pant_j @ fia_j) / den\n",
    "            teta_ant = self.teta_ea[sl]\n",
    "            self.teta_ea[sl] = teta_ant + kk_j * (P_k_medido - teta_ant @ fia_j)\n",
    "            self.Pant[sl, sl] = (np.eye(3) - np.outer(kk_j, fia_j)) @ Pant_j / self.lambda_val\n",
    "            ep = (P_k_medido - self.teta_ea[sl] @ fia_j)**2\n",
    "            self.histo_erro[self.k-1, j] = ep\n",
    "            janela = 20\n",
    "            ini = max(0, self.k - janela)\n",
    "            self.fator[j] = np.sum(self.histo_erro[ini:self.k, j])\n",
    "            Soma_mi += 1.0 / (self.fator[j] + 1e-9)\n",
    "\n",
    "        Med_adeq = np.array([1.0/(self.fator[j]+1e-9) for j in range(4)]) / (Soma_mi + 1e-9)\n",
    "        ind_cand = np.argmax(Med_adeq)\n",
    "        if Med_adeq[ind_cand] > 1.35 * Med_adeq[self.ind_melhor]:\n",
    "            self.ind_melhor = ind_cand\n",
    "\n",
    "        sl_best = slice(3*self.ind_melhor, 3*self.ind_melhor+3)\n",
    "        self.teta_melhor = self.teta_ea[sl_best]\n",
    "        incertezas = np.diagonal(self.Pant)[[1, 4, 7, 10]]\n",
    "        P_melhor = self.Pant[sl_best, sl_best].copy()\n",
    "        return self.teta_melhor, self.d_vetor[self.ind_melhor], self.m_vetor[self.ind_melhor], incertezas, self.fator.copy(), P_melhor\n"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
